### ISSUE TITLE
License? 

### ISSUE THREAD

**Issue by pathtofile** [itm4n/PPLdump#2]
Hey mate, awesome work! Is your code under any license (free like bsd, or otherwise)?

I'd like to make use of your PPL-injecting code alongside another open source project of mine, but I wanted to make sure that apart from giving you and your dope work every kudos/acknowledgement I can, there's no sorta legal issue with it.

**Comment by itm4n** [comment]
Hey!
No, there is no particular license. A simple acknowledgement is perfectly fine to me. :slightly_smiling_face:
Thanks.

**Comment by pathtofile** [comment]
Great, thanks!
